// <auto-generated />
namespace WindowsFormsApp_Koodrizi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adddkoodtoavgModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddkoodtoavgModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202102130810019_add-dkood-to-avgModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
